server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://account-db:5432/account-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    url: jdbc:postgresql://account-db:5432/account-db
    user: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: caffeine
    cache-names: currencies
    caffeine:
      spec: maximumSize=1,expireAfterWrite=10m

  security:
    oauth2:
      client:
        registration:
          bank:
            client-id: account-client
            client-secret: sJqfAimSEzt5X1gSdnIEZX8IS5dlhMmF
  data:
    redis:
      host: block-token-list-db
      port: 6379
      timeout: 5s

account:
  balance:
    lock-timeout-seconds: 2

