spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}

    openfeign:
      client:
        config:
          account-service:
            url: http://localhost:8080/account
          account-balance-service:
            url: http://localhost:8080/account/balance
          account-auth-service:
            url: http://localhost:8080/account/auth
          blocker-service:
            url: http://localhost:8080/blocker
          transfer-service:
            url: http://localhost:8080/transfer
          cash-service:
            url: http://localhost:8080/cash
          exchange-service:
            url: http://localhost:8080/exchange
          notification-service:
            url: http://localhost:8080/notification

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/bank
        registration:
          bank:
            provider: keycloak
            authorization-grant-type: client_credentials
            scope: profile
            client-authentication-method: client_secret_post
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/bank

sso:
  client-registration-id: bank

jwt:
  login-header-name: X-User-Login
  access-token-name: accessToken
  refresh-token-name: refreshToken
  secret: YmFzZTY0ZW5jb2RlZGtleWZvckhzNTExMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
  access-expiration: 1200     # 10 минут
  refresh-expiration: 86400  # 24 часа

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

