server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        health-check-path: /actuator/health
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}

    gateway:
      httpheaders:
        propagate-request-handler: true
      forwarded:
        enabled: true
      routes:

        - id: front-ui-service
          uri:  lb://front-ui-service
          predicates:
            - Path=/, /main, /login, /signup, /css/**, /js/**, /images/**, /favicon.ico
          filters:
            - RewritePath=/(?<segment>.*), /front/${segment}

        - id: account-front-ui-service
          uri: lb://front-ui-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /front/account/${segment}

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=0

        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**
          filters:
            - StripPrefix=0

        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/cash/**
          filters:
            - StripPrefix=0

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**
          filters:
            - StripPrefix=0

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=0

        - id: blocker-service
          uri: lb://blocker-service
          predicates:
            - Path=/blocker/**
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true





